/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewerynjagusiak.pl.largefileviewer.views;

import java.awt.Toolkit;

/**
 *
 * @author Seweryn
 */
public class MainWindow extends javax.swing.JFrame {

    public MainWindow() {
        this.initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/sewerynjagusiak/pl/largefileviewer/img/lvf.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lfvMWToolbar = new javax.swing.JToolBar();
        lfvMWReloadButton = new javax.swing.JButton();
        lfvMWNextButton = new javax.swing.JButton();
        lfvMWSeparator = new javax.swing.JToolBar.Separator();
        lfvMWInfoLabel = new javax.swing.JLabel();
        lfvMWDisplayScroll = new javax.swing.JScrollPane();
        lfvMWDisplay = new javax.swing.JTextArea();
        lfvMWMenu = new javax.swing.JMenuBar();
        lfvMWFileMenu = new javax.swing.JMenu();
        lfvMWFileMenuOpen = new javax.swing.JMenuItem();
        lfvMWFileMenuSeparator = new javax.swing.JPopupMenu.Separator();
        lfvMWFileMenuAbout = new javax.swing.JMenuItem();
        lfvMWFileMenuClose = new javax.swing.JMenuItem();
        lfvMWActionMenu = new javax.swing.JMenu();
        lfvMWActionMenuNext = new javax.swing.JMenuItem();
        lfvMWActionMenuReload = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Large File Viewer");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setLocationByPlatform(true);

        lfvMWToolbar.setFloatable(false);
        lfvMWToolbar.setRollover(true);

        lfvMWReloadButton.setText("Reload");
        lfvMWReloadButton.setEnabled(false);
        lfvMWReloadButton.setFocusable(false);
        lfvMWReloadButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lfvMWReloadButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lfvMWToolbar.add(lfvMWReloadButton);

        lfvMWNextButton.setText("Next");
        lfvMWNextButton.setEnabled(false);
        lfvMWNextButton.setFocusable(false);
        lfvMWNextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lfvMWNextButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lfvMWToolbar.add(lfvMWNextButton);
        lfvMWToolbar.add(lfvMWSeparator);

        lfvMWInfoLabel.setText("...");
        lfvMWToolbar.add(lfvMWInfoLabel);

        lfvMWDisplay.setEditable(false);
        lfvMWDisplay.setColumns(20);
        lfvMWDisplay.setFont(lfvMWDisplay.getFont().deriveFont(lfvMWDisplay.getFont().getSize()+3f));
        lfvMWDisplay.setRows(5);
        lfvMWDisplayScroll.setViewportView(lfvMWDisplay);

        lfvMWFileMenu.setText("File");

        lfvMWFileMenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        lfvMWFileMenuOpen.setText("Open");
        lfvMWFileMenu.add(lfvMWFileMenuOpen);
        lfvMWFileMenu.add(lfvMWFileMenuSeparator);

        lfvMWFileMenuAbout.setText("About");
        lfvMWFileMenu.add(lfvMWFileMenuAbout);

        lfvMWFileMenuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        lfvMWFileMenuClose.setText("Close");
        lfvMWFileMenu.add(lfvMWFileMenuClose);

        lfvMWMenu.add(lfvMWFileMenu);

        lfvMWActionMenu.setText("Action");

        lfvMWActionMenuNext.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PERIOD, java.awt.event.InputEvent.CTRL_MASK));
        lfvMWActionMenuNext.setText("Next");
        lfvMWActionMenu.add(lfvMWActionMenuNext);

        lfvMWActionMenuReload.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        lfvMWActionMenuReload.setText("Reload");
        lfvMWActionMenu.add(lfvMWActionMenuReload);

        lfvMWMenu.add(lfvMWActionMenu);

        setJMenuBar(lfvMWMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lfvMWToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lfvMWDisplayScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lfvMWDisplayScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lfvMWToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenu lfvMWActionMenu;
    public javax.swing.JMenuItem lfvMWActionMenuNext;
    public javax.swing.JMenuItem lfvMWActionMenuReload;
    public javax.swing.JTextArea lfvMWDisplay;
    public javax.swing.JScrollPane lfvMWDisplayScroll;
    public javax.swing.JMenu lfvMWFileMenu;
    public javax.swing.JMenuItem lfvMWFileMenuAbout;
    public javax.swing.JMenuItem lfvMWFileMenuClose;
    public javax.swing.JMenuItem lfvMWFileMenuOpen;
    public javax.swing.JPopupMenu.Separator lfvMWFileMenuSeparator;
    public javax.swing.JLabel lfvMWInfoLabel;
    public javax.swing.JMenuBar lfvMWMenu;
    public javax.swing.JButton lfvMWNextButton;
    public javax.swing.JButton lfvMWReloadButton;
    public javax.swing.JToolBar.Separator lfvMWSeparator;
    public javax.swing.JToolBar lfvMWToolbar;
    // End of variables declaration//GEN-END:variables
}
