/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewerynjagusiak.pl.largefileviewer.views;

/**
 *
 * @author Seweryn
 */
public class OpenWindow extends javax.swing.JFrame {

    /**
     * Creates new form OpenWindow
     */
    public OpenWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lfvOFPanel = new javax.swing.JPanel();
        lfvOFChooseFileLabel = new javax.swing.JLabel();
        lfvOFChooseFilePath = new javax.swing.JTextField();
        lfvOFChooseFileButton = new javax.swing.JButton();
        lfvOFTopSeparator = new javax.swing.JSeparator();
        lfvOFChunkMethod = new javax.swing.JLabel();
        lfvOFChunkMethodLines = new javax.swing.JRadioButton();
        lfvOFChunkMethodLinesValue = new javax.swing.JSpinner();
        lfvOFSubmitView = new javax.swing.JButton();

        setTitle("Select file");
        setIconImages(null);
        setLocationByPlatform(false);
        setType(java.awt.Window.Type.UTILITY);

        lfvOFChooseFileLabel.setText("Choose File:");

        lfvOFChooseFilePath.setEditable(false);

        lfvOFChooseFileButton.setText("Select");

        lfvOFChunkMethod.setText("Chunk method:");

        lfvOFChunkMethodLines.setSelected(true);
        lfvOFChunkMethodLines.setText("lines:");

        lfvOFChunkMethodLinesValue.setModel(new javax.swing.SpinnerNumberModel(1000, 1, null, 500));

        lfvOFSubmitView.setText("View");
        lfvOFSubmitView.setEnabled(false);

        javax.swing.GroupLayout lfvOFPanelLayout = new javax.swing.GroupLayout(lfvOFPanel);
        lfvOFPanel.setLayout(lfvOFPanelLayout);
        lfvOFPanelLayout.setHorizontalGroup(
            lfvOFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lfvOFPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lfvOFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lfvOFTopSeparator)
                    .addGroup(lfvOFPanelLayout.createSequentialGroup()
                        .addGroup(lfvOFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lfvOFChooseFileLabel)
                            .addComponent(lfvOFChunkMethod)
                            .addGroup(lfvOFPanelLayout.createSequentialGroup()
                                .addComponent(lfvOFChunkMethodLines)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lfvOFChunkMethodLinesValue, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 262, Short.MAX_VALUE))
                    .addGroup(lfvOFPanelLayout.createSequentialGroup()
                        .addComponent(lfvOFChooseFilePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lfvOFChooseFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lfvOFSubmitView)))
                .addContainerGap())
        );
        lfvOFPanelLayout.setVerticalGroup(
            lfvOFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lfvOFPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lfvOFChooseFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lfvOFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lfvOFChooseFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lfvOFChooseFileButton)
                    .addComponent(lfvOFSubmitView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lfvOFTopSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lfvOFChunkMethod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lfvOFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lfvOFChunkMethodLines)
                    .addComponent(lfvOFChunkMethodLinesValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lfvOFPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lfvOFPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton lfvOFChooseFileButton;
    public javax.swing.JLabel lfvOFChooseFileLabel;
    public javax.swing.JTextField lfvOFChooseFilePath;
    public javax.swing.JLabel lfvOFChunkMethod;
    public javax.swing.JRadioButton lfvOFChunkMethodLines;
    public javax.swing.JSpinner lfvOFChunkMethodLinesValue;
    public javax.swing.JPanel lfvOFPanel;
    public javax.swing.JButton lfvOFSubmitView;
    public javax.swing.JSeparator lfvOFTopSeparator;
    // End of variables declaration//GEN-END:variables
}
